const words = [
    { bulgarian: "леля", english: "aunt" },
    { bulgarian: "чичо", english: "uncle" },
    { bulgarian: "братовчед", english: "cousin" },
    { bulgarian: "почивка", english: "holiday" },
    { bulgarian: "летище", english: "airport" },
    { bulgarian: "африка", english: "Africa" },
    { bulgarian: "англия", english: "England" },
    { bulgarian: "сос", english: "sauce" },
    { bulgarian: "срамежлив", english: "shy" },
    { bulgarian: ["изморен", "уморен"], english: "tired" },
    { bulgarian: "гладен", english: "hungry" },
    { bulgarian: "шорти", english: "shorts" },
    { bulgarian: "риза", english: "shirt" },
    { bulgarian: "карта", english: "map" },
    { bulgarian: "камера", english: "camera" },
    { bulgarian: "слънчеви очила", english: "sunglasses" },
    { bulgarian: "бански", english: "swimsuit" },
    { bulgarian: "усмивка", english: "smile" },
    { bulgarian: "самолет", english: ["plane", "airplane"] },
    { bulgarian: "такси", english: "taxi" },
    { bulgarian: "паспорт", english: "passport" },
    { bulgarian: "билет", english: "ticket" },
    { bulgarian: "пари", english: "money" },
    { bulgarian: "куфар", english: "suitcase" },
    { bulgarian: "математика", english: ["maths", "mathematics"] },
    { bulgarian: "английски", english: "english" },
    { bulgarian: "история", english: "history" },
    { bulgarian: "изкуство", english: "art" },
    { bulgarian: "динозавър", english: "dinosaur" },
    { bulgarian: "физическо възпитание", english: ["p.e.", "physical education", "pe", "p.e"] },
    { bulgarian: "сутрин", english: "morning" },
    { bulgarian: "следобед", english: "afternoon" },
    { bulgarian: "вечер", english: "evening" }, 
    { bulgarian: "пощальон", english: "postman" },
    { bulgarian: "пощенска картичка", english: "postcard" },
    { bulgarian: "колет", english: "parcel" },
    { bulgarian: "плаж", english: "beach" },
    { bulgarian: "осем и половина", english: "half past eight" },
    { bulgarian: "уикенд", english: "weekend" },
    { bulgarian: "година", english: "year" },
    { bulgarian: "зима", english: "winter" },
    { bulgarian: "лято", english: "summer" },
    { bulgarian: ["фото албум","албум за снимки"], english: "photo album" },
    { bulgarian: "планина", english: "mountain" },
    { bulgarian: "ски", english: "ski" },
    { bulgarian: "панда", english: "panda" },
    { bulgarian: "китай", english: "china" },
    { bulgarian: "листа", english: "leaves" },
    { bulgarian: "месо", english: "meat" },
    { bulgarian: "буден", english: "awake" },
    { bulgarian: "развълнуван", english: "excited" },
    { bulgarian: "птица", english: "bird" },
    { bulgarian: "показвам", english: "show" },
    { bulgarian: "събуждам се", english: "wake up" },
    { bulgarian: "искам", english: "want" },
    { bulgarian: "рано", english: "early" },
    { bulgarian: "късно", english: "late" },
    { bulgarian: "побързай", english: "hurry up" },
    { bulgarian: "купа", english: "cup" },
    { bulgarian: "звънец", english: "doorbell" },
    { bulgarian: "дом", english: "home" },
    { bulgarian: "готвя", english: "cook" },
    { bulgarian: "звъня", english: "ring" },
    { bulgarian: "отегчен", english: "bored" },
    { bulgarian: "чинии", english: "dishes" },
    { bulgarian: "под", english: "floor" },
    { bulgarian: "ягода", english: "strawberry" },
    { bulgarian: "правя", english: "make" },
    { bulgarian: "мия", english: "wash" },
    { bulgarian: "супермаркет", english: "supermarket" },
    { bulgarian: "библиотека", english: "library" },
    { bulgarian: "кино", english: ["cinema", "movie theatre"] },
    { bulgarian: "храна", english: "food" },
    { bulgarian: "въже", english: "rope" },
    { bulgarian: ["отивам да пазарувам", "да пазарувам", "отивам на шопинг"], english: "go shopping" },
    { bulgarian: "купувам", english: "buy" },
    { bulgarian: "череша", english: "cherry" },
    { bulgarian: "портокал", english: "orange" },
    { bulgarian: "жаден", english: "thirsty" },
    { bulgarian: "праскова", english: "peach" },
    { bulgarian: "диня", english: "watermelon" },
    { bulgarian: "чаша", english: "glass" },
    { bulgarian: "сламка", english: "straw" },
    { bulgarian: "сок", english: "juice" },
    { bulgarian: "хладилник", english: ["fridge", "refrigerator"] },
    { bulgarian: "вода", english: "water" },
    { bulgarian: "брашно", english: "flour" },
    { bulgarian: "захар", english: "sugar" },
    { bulgarian: "масло", english: "butter" },
    { bulgarian: "бисквита", english: "biscuit" },
    { bulgarian: "стена", english: "wall" },
    { bulgarian: "катерица", english: "squirrel" },
    { bulgarian: "малък", english: ["small", "little"] },
    { bulgarian: "детектив", english: "detective" },
    { bulgarian: "умен", english: ["smart", "clever"] },
    { bulgarian: "лаптоп", english: "laptop" },
    { bulgarian: "внимателно", english: "carefully" },
    { bulgarian: "лошо", english: "badly" },
    { bulgarian: "добре", english: "well" },
    { bulgarian: "бавно", english: "slowly" },
    { bulgarian: "тихо", english: "quietly" },
    { bulgarian: "весело", english: "happily" },
    { bulgarian: "бързо", english: "quickly" },
];